name: 'lowercase-only'
author: Julie Ng
description: 'Lint repos for mixed case names, i.e. camelCase to prevent filename conflicts and broken deployments to Linux.'
inputs:
  path:
    description: 'Path to scan for mixed case filenames. Will search subfolders too. Defaults to `.`'
    required: false
    default: '.'
  pr-comment:
    description: 'If file name errors are found, suggested fixes are posted to the Pull Request'
    required: true
    default: false
  repo-token:
    description: repo workflow token
    required: false
    default: ''
outputs:
  errors:
    description: 'Array of files with mixed case and suggested renames in JSON.'
  linted:
    description: 'List of files linted.'
  comment-url:
    description: 'URL of the comment posted to Pull Request (if errors were found).'
runs:
  using: 'node16'
  main: 'dist/index.js'