name: ci

on:
  push:
    branches:
      - 'dev'
      - 'main'
      - 'feat/*'
      - 'fix/*'
    paths-ignore:
      - '**.md'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci
      - run: npm audit
        continue-on-error: true # only dev deps in this repo

      - run: npm run lint
      - run: npm run test
      - run: node ./lint-fixtures.js

  coverage:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      GIT_BRANCH: ${{ github.ref_name }}
      GIT_COMMIT: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: setup reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter  before-build

      - name: publish report
        run: |
          npm ci
          npm run test
          npm run coverage
          ./cc-test-reporter format-coverage coverage/clover.xml --input-type clover
          ./cc-test-reporter upload-coverage
