name: run-action

on:
  push:
    branches:
      - 'dev'
      - 'main'
      - 'test-pr'
    paths:
      - 'dist/**.js' # otherwise there's no real change in action
jobs:
  passing_scenarios:
    runs-on: ubuntu-latest
    name: Passing use case
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint Valid Fixtures
        uses: ./ # this repo
        id: run_passing
        with:
          path: 'fixtures/always-passing'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Outputs
        run: echo "${{ toJSON(steps.run_passing.outputs }}"

  failing_scenarios:
    runs-on: ubuntu-latest
    name: Failing use case
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint Invalid Fixtures
        uses: ./ # this repo
        id: run_failing
        continue-on-error: true
        with:
          path: 'fixtures/'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Outputs
        run: echo "${{ toJSON(steps.run_failing.outputs) }}"

      - name: Confirm Fixtures Failed
        run: |
          if [[ ${{ steps.run_failing.outcome }} == 'failure' ]]; then exit 0; else exit 1; fi
